//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace f12020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class piloto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public piloto()
        {
            this.grid = new HashSet<grid>();
        }
    
        public int id_piloto { get; set; }
        public string nome { get; set; }
        public string sobrenome { get; set; }
        public int equipe_id_equipe { get; set; }
    
        public virtual equipe equipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grid> grid { get; set; }
    }
}
