//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace f12020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_token
    {
        public int id { get; set; }
        public int usuario_id_usuario { get; set; }
        public int num_acessos { get; set; }
        public string token { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
